/// Dietetics & clinical nutrition entities (Module 21).
///
/// Flow: assessment (draft -> finalized) -> seven-day meal plan -> approval ->
/// intake. A finalized assessment and a decided plan are frozen, so the
/// version the ward administers stays readable exactly as authorized.
// ignore_for_file: sort_constructors_first
library;

import 'package:meta/meta.dart';

/// The number of days in a meal plan cycle.
///
/// A clinical nutrition plan is authored as a full week so the ward can
/// administer it without further decisions, and approval requires the whole
/// cycle to be present.
const int dietCycleDays = 7;

/// Kind of clinical nutrition assessment.
enum DietAssessmentType {
  initial('initial'),
  reassessment('reassessment');

  const DietAssessmentType(this.wireValue);

  final String wireValue;

  String get label => switch (this) {
    DietAssessmentType.initial => 'Initial assessment',
    DietAssessmentType.reassessment => 'Reassessment',
  };

  static DietAssessmentType fromWire(String value) =>
      DietAssessmentType.values.firstWhere(
        (DietAssessmentType type) => type.wireValue == value,
        orElse: () => DietAssessmentType.initial,
      );
}

/// Lifecycle of a nutrition assessment.
enum DietAssessmentStatus {
  draft('draft'),
  finalized('finalized');

  const DietAssessmentStatus(this.wireValue);

  final String wireValue;

  String get label => switch (this) {
    DietAssessmentStatus.draft => 'Draft',
    DietAssessmentStatus.finalized => 'Finalized',
  };

  bool get isDraft => this == draft;

  bool get isFinalized => this == finalized;

  bool get isTerminal => this == finalized;

  static DietAssessmentStatus fromWire(String value) =>
      DietAssessmentStatus.values.firstWhere(
        (DietAssessmentStatus status) => status.wireValue == value,
        orElse: () => DietAssessmentStatus.draft,
      );
}

/// Origin of a meal plan.
enum DietPlanSource {
  aiGenerated('ai_generated'),
  clinicianAuthored('clinician_authored');

  const DietPlanSource(this.wireValue);

  final String wireValue;

  String get label => switch (this) {
    DietPlanSource.aiGenerated => 'AI generated',
    DietPlanSource.clinicianAuthored => 'Clinician authored',
  };

  /// Whether the plan was generated by a model and therefore needs explicit
  /// clinical approval before it takes effect.
  bool get isAiGenerated => this == aiGenerated;

  static DietPlanSource fromWire(String value) =>
      DietPlanSource.values.firstWhere(
        (DietPlanSource source) => source.wireValue == value,
        orElse: () => DietPlanSource.clinicianAuthored,
      );
}

/// Lifecycle of a meal plan.
enum DietMealPlanStatus {
  draft('draft'),
  approved('approved'),
  rejected('rejected');

  const DietMealPlanStatus(this.wireValue);

  final String wireValue;

  String get label => switch (this) {
    DietMealPlanStatus.draft => 'Draft',
    DietMealPlanStatus.approved => 'Approved',
    DietMealPlanStatus.rejected => 'Rejected',
  };

  bool get isDraft => this == draft;

  bool get isApproved => this == approved;

  bool get isTerminal => this == approved || this == rejected;

  static DietMealPlanStatus fromWire(String value) =>
      DietMealPlanStatus.values.firstWhere(
        (DietMealPlanStatus status) => status.wireValue == value,
        orElse: () => DietMealPlanStatus.draft,
      );
}

/// Meal of the day an intake record refers to.
enum DietMealSlot {
  breakfast('breakfast'),
  lunch('lunch'),
  dinner('dinner'),
  snacks('snacks');

  const DietMealSlot(this.wireValue);

  final String wireValue;

  String get label => switch (this) {
    DietMealSlot.breakfast => 'Breakfast',
    DietMealSlot.lunch => 'Lunch',
    DietMealSlot.dinner => 'Dinner',
    DietMealSlot.snacks => 'Snacks',
  };

  static DietMealSlot fromWire(String value) => DietMealSlot.values.firstWhere(
    (DietMealSlot slot) => slot.wireValue == value,
    orElse: () => DietMealSlot.breakfast,
  );
}

/// A clinical nutrition assessment, frozen once finalized.
@immutable
final class DietAssessment {
  const DietAssessment({
    required this.id,
    required this.tenantId,
    required this.patientId,
    required this.assessedBy,
    required this.assessmentType,
    required this.nutritionDiagnosis,
    required this.status,
    required this.assessedAt,
    required this.createdAt,
    required this.updatedAt,
    this.encounterId,
    this.weightKg,
    this.heightCm,
    this.restrictions,
    this.finalizedAt,
    this.finalizedBy,
  });

  factory DietAssessment.fromRow(Map<String, Object?> row) {
    final Object? encounter = row['encounter_id'];
    final Object? weight = row['weight_kg'];
    final Object? height = row['height_cm'];
    final Object? restrictions = row['restrictions'];
    final Object? finalizedAt = row['finalized_at'];
    final Object? finalizedBy = row['finalized_by'];
    return DietAssessment(
      id: row['id']! as String,
      tenantId: row['tenant_id']! as String,
      patientId: row['patient_id']! as String,
      encounterId: encounter is String ? encounter : null,
      assessedBy: row['assessed_by']! as String,
      assessmentType: DietAssessmentType.fromWire(
        row['assessment_type']! as String,
      ),
      weightKg: weight is num ? weight.toDouble() : null,
      heightCm: height is num ? height.toDouble() : null,
      nutritionDiagnosis: row['nutrition_diagnosis']! as String,
      restrictions: restrictions is String ? restrictions : null,
      status: DietAssessmentStatus.fromWire(row['status']! as String),
      assessedAt: row['assessed_at']! as DateTime,
      finalizedAt: finalizedAt is DateTime ? finalizedAt : null,
      finalizedBy: finalizedBy is String ? finalizedBy : null,
      createdAt: row['created_at']! as DateTime,
      updatedAt: row['updated_at']! as DateTime,
    );
  }

  final String id;
  final String tenantId;
  final String patientId;
  final String? encounterId;
  final String assessedBy;
  final DietAssessmentType assessmentType;
  final double? weightKg;
  final double? heightCm;
  final String nutritionDiagnosis;
  final String? restrictions;
  final DietAssessmentStatus status;
  final DateTime assessedAt;
  final DateTime? finalizedAt;
  final String? finalizedBy;
  final DateTime createdAt;
  final DateTime updatedAt;

  bool get isDraft => status.isDraft;

  bool get isFinalized => status.isFinalized;
}

/// A seven-day meal plan, decided by approval or rejection.
@immutable
final class DietMealPlan {
  const DietMealPlan({
    required this.id,
    required this.tenantId,
    required this.patientId,
    required this.assessmentId,
    required this.name,
    required this.planSource,
    required this.cycleDays,
    required this.status,
    required this.createdAt,
    required this.updatedAt,
    this.generatedBy,
    this.generatedAt,
    this.approvedBy,
    this.approvedAt,
    this.rejectedBy,
    this.rejectedAt,
    this.rejectionReason,
  });

  factory DietMealPlan.fromRow(Map<String, Object?> row) {
    final Object? generatedBy = row['generated_by'];
    final Object? generatedAt = row['generated_at'];
    final Object? approvedBy = row['approved_by'];
    final Object? approvedAt = row['approved_at'];
    final Object? rejectedBy = row['rejected_by'];
    final Object? rejectedAt = row['rejected_at'];
    final Object? rejectionReason = row['rejection_reason'];
    return DietMealPlan(
      id: row['id']! as String,
      tenantId: row['tenant_id']! as String,
      patientId: row['patient_id']! as String,
      assessmentId: row['assessment_id']! as String,
      name: row['name']! as String,
      planSource: DietPlanSource.fromWire(row['plan_source']! as String),
      cycleDays: (row['cycle_days']! as num).toInt(),
      status: DietMealPlanStatus.fromWire(row['status']! as String),
      generatedBy: generatedBy is String ? generatedBy : null,
      generatedAt: generatedAt is DateTime ? generatedAt : null,
      approvedBy: approvedBy is String ? approvedBy : null,
      approvedAt: approvedAt is DateTime ? approvedAt : null,
      rejectedBy: rejectedBy is String ? rejectedBy : null,
      rejectedAt: rejectedAt is DateTime ? rejectedAt : null,
      rejectionReason: rejectionReason is String ? rejectionReason : null,
      createdAt: row['created_at']! as DateTime,
      updatedAt: row['updated_at']! as DateTime,
    );
  }

  final String id;
  final String tenantId;
  final String patientId;
  final String assessmentId;
  final String name;
  final DietPlanSource planSource;
  final int cycleDays;
  final DietMealPlanStatus status;
  final String? generatedBy;
  final DateTime? generatedAt;
  final String? approvedBy;
  final DateTime? approvedAt;
  final String? rejectedBy;
  final DateTime? rejectedAt;
  final String? rejectionReason;
  final DateTime createdAt;
  final DateTime updatedAt;

  bool get isDraft => status.isDraft;

  bool get isApproved => status.isApproved;

  bool get isTerminal => status.isTerminal;
}

/// One day's menu within a seven-day cycle.
@immutable
final class DietMealPlanDay {
  const DietMealPlanDay({
    required this.id,
    required this.tenantId,
    required this.mealPlanId,
    required this.dayNumber,
    required this.breakfast,
    required this.lunch,
    required this.dinner,
    required this.caloriesKcal,
    required this.createdAt,
    required this.updatedAt,
    this.snacks,
  });

  factory DietMealPlanDay.fromRow(Map<String, Object?> row) {
    final Object? snacks = row['snacks'];
    return DietMealPlanDay(
      id: row['id']! as String,
      tenantId: row['tenant_id']! as String,
      mealPlanId: row['meal_plan_id']! as String,
      dayNumber: (row['day_number']! as num).toInt(),
      breakfast: row['breakfast']! as String,
      lunch: row['lunch']! as String,
      dinner: row['dinner']! as String,
      snacks: snacks is String ? snacks : null,
      caloriesKcal: (row['calories_kcal']! as num).toInt(),
      createdAt: row['created_at']! as DateTime,
      updatedAt: row['updated_at']! as DateTime,
    );
  }

  final String id;
  final String tenantId;
  final String mealPlanId;
  final int dayNumber;
  final String breakfast;
  final String lunch;
  final String dinner;
  final String? snacks;
  final int caloriesKcal;
  final DateTime createdAt;
  final DateTime updatedAt;
}

/// A record of the portion of a planned meal actually taken.
@immutable
final class DietIntakeLog {
  const DietIntakeLog({
    required this.id,
    required this.tenantId,
    required this.patientId,
    required this.mealPlanDayId,
    required this.mealSlot,
    required this.portionConsumedPct,
    required this.recordedBy,
    required this.recordedAt,
    required this.createdAt,
    required this.updatedAt,
  });

  factory DietIntakeLog.fromRow(Map<String, Object?> row) => DietIntakeLog(
    id: row['id']! as String,
    tenantId: row['tenant_id']! as String,
    patientId: row['patient_id']! as String,
    mealPlanDayId: row['meal_plan_day_id']! as String,
    mealSlot: DietMealSlot.fromWire(row['meal_slot']! as String),
    portionConsumedPct: (row['portion_consumed_pct']! as num).toInt(),
    recordedBy: row['recorded_by']! as String,
    recordedAt: row['recorded_at']! as DateTime,
    createdAt: row['created_at']! as DateTime,
    updatedAt: row['updated_at']! as DateTime,
  );

  final String id;
  final String tenantId;
  final String patientId;
  final String mealPlanDayId;
  final DietMealSlot mealSlot;
  final int portionConsumedPct;
  final String recordedBy;
  final DateTime recordedAt;
  final DateTime createdAt;
  final DateTime updatedAt;
}
